[build]
builder = "nixpacks"
buildCommand = "yarn install --no-optional && yarn build"

[deploy]
startCommand = "yarn serve"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "never"