/* tslint:disable */
/**
 * This file was automatically generated by Payload CMS.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  collections: {
    prompts: Prompt;
    roles: Role;
    users: User;
  };
  globals: {};
}
export interface Prompt {
  id: string;
  model: 'gpt-3.5-turbo' | 'gpt-4' | 'gpt-4-32k';
  name: string;
  description?: string;
  role?: string | Role;
  prompt: string;
  validation: {
    validationEnabled?: boolean;
    maxRetries?: number;
    validationFunction?: string;
  };
  rateLimit: {
    rateLimitEnabled?: boolean;
    requestsPerUnit?: number;
    timeUnit?: 'minute' | 'hour' | 'day' | 'month';
  };
  redaction: {
    redactionEnabled?: boolean;
    redactionMode?: 'redact' | 'fail';
  };
  createdAt: string;
  updatedAt: string;
}
export interface Role {
  id: string;
  name: string;
  value: string;
  createdAt: string;
  updatedAt: string;
}
export interface User {
  id: string;
  email?: string;
  resetPasswordToken?: string;
  resetPasswordExpiration?: string;
  loginAttempts?: number;
  lockUntil?: string;
  createdAt: string;
  updatedAt: string;
  password?: string;
}
